version: '3.5'
services:
  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: playlist_db
      POSTGRES_USER: default
      POSTGRES_PASSWORD: example
    volumes:
      - ./internal/repository/migrations:/docker-entrypoint-initdb.d
      - /opt/databases/user_server_postgres:/var/lib/postgresql/data