version: '3.5'
services:
  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./internal/repository/migrations:/docker-entrypoint-initdb.d
      - /opt/databases/playlist_server_postgres:/var/lib/postgresql/data

  playlist:
    image: playlist:latest
    container_name: playlist
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      PG_HOST: postgres
    depends_on:
      - postgres
